### ISSUE TITLE
Getting a "None: Value" error when scraping a URL

### ISSUE THREAD

**Issue by sgriffiths** [alfinsuryaS/reason-rust-scraper#2]
I followed the setup and seem to have everything running.

When i scrape any URL I am getting the following error:
`thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', server/lib/scrapper.rs:80:36`

Is this indicating there is an issue unwrapping the 'href' response that's coming back ?

Any ideas what the problem could be here ? As the tests pass fine and everything looks to be operational

**Comment by natserract** [comment]
Hello @sgriffiths thankyou for the issue. Can you provide site url you want to scrap?

**Comment by sgriffiths** [comment]
Hi, This happens for any URL that I try and scrape. 
For that sake of providing an example:
https://www.google.com/search?q=google+coronavirus 
@natserract

**Comment by natserract** [comment]
Sorry, for that's url, in my device is works. Maybe you getting blocked, i think you can set your IP address and proxy in your device, or you can using VPN:

![Screen Shot 2020-04-13 at 16 07 35](https://user-images.githubusercontent.com/31182611/79104538-5eafaf00-7da1-11ea-804c-7e8f8f729229.png)

**Comment by sgriffiths** [comment]
Hi, Tried all those combinations as you mentioned. And still had no luck. Pulled down everything again and managed to get it working in FF. Cheers for confirming is was working
